# Generated by Django 3.2.6 on 2021-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('data_inicio_tarefa', models.DateTimeField(auto_now_add=True)),
                ('data_do_termino', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
    ]
