# Generated by Django 3.2.6 on 2021-08-09 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_do_termino',
            field=models.DateTimeField(auto_now=True, verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_inicio_tarefa',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Check-in'),
        ),
    ]
