# Generated by Django 3.2.6 on 2021-08-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20210809_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='data_inicio_tarefa',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='data_do_termino',
            new_name='data_termino',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='slug',
        ),
    ]
